delay: 1000
servers:
- description: main server
  protocol: http
  host: localhost
  port: 15672
  user: guest
  password: guest
  rules:
  - description: /lophutch/test1 should be properly consumed
    request:
    - method: GET
      path: /api/queues/lophutch/test1
    evaluator: |-
      function evaluate(response) {
        if (response.messages_ready > 100)
          return true
        if (response.consumers < 2)
          return true
        return false
      }
    next-action-delay: 30000
    actions:
    - description: notify via Slack
      cmd: send-msg-slack
      args:
      - "--channel"
      - "#critical"
      - "--message"
      - "/lophutch/test1 is not being properly consumed, running a new container"
    - description: run a new container
      cmd: run-container
      args:
      - "--image"
      - "test1"